Djojo/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView
from engine.views import UserProfileDetailView
admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^users/', include('registration.backends.simple.urls')),
    
    url(r'^$','engine.views.home', name='home'),
    url(r'^dojo/', include('dojo.urls'), name='dojo'),
    url(r'^documents/', include('documents.urls', namespace='documents'), name='documents'),
    
    url(r'^users/(?P<slug>\w+)/$', UserProfileDetailView.as_view(), name="profile"),
    
    #fix per django 1.6
    #http://stackoverflow.com/questions/19985103/
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    
    url(r'^users/register/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register'),
)


urlpatterns += patterns('',
     (r'^static/(?P<path>.*)$', 'django.views.static.serve',
    # {'document_root': settings.MEDIA_ROOT}),
    #{'document_root': settings.MEDIA_ROOT, 'show_indexes': True},
    {'document_root': settings.STATIC_ROOT, 'show_indexes': True})
)

handler403 = 'engine.views.custom403'

blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'^$',views.index, name='index'),
    #url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<slug>.*)/$', views.detail, name='detail'),
)

documents/urls.py
from django.contrib.auth.decorators import permission_required
from django.conf.urls import patterns, url

from .views import Add_document, Edit_document, Delete_document, documents_list

urlpatterns = patterns('',
   url(r'^$', documents_list, name='list'),
   url(r'^new/$', Add_document.as_view(), name='add'),
   url(r'^(?P<pk>\d+)/edit/$', Edit_document.as_view(), name='edit'),
   url(r'^(?P<pk>\d+)/delete/$', Delete_document.as_view(), name='delete'),
)

documents/models.py
from django.db import models
from django.contrib.auth.models import User


class Document(models.Model):
    title = models.CharField('Titolo', max_length=150)
    uploadedfile = models.FileField(upload_to='./documents')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

documents/views.py
from django.shortcuts import render
from django.views.generic.edit import DeleteView
from django.views import generic
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse_lazy

from .models import Document


@permission_required('documents.view_documents', raise_exception=True)
def documents_list(request):
    document_list = Document.objects.order_by('title')
    paginator = Paginator(document_list, 25)

    page = request.GET.get('page')
    try:
        document_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        document_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        document_list = paginator.page(paginator.num_pages)

    return render_to_response('documents/document_list.html', {"document_list": document_list},
                              context_instance=RequestContext(request))


class Add_document(generic.CreateView):
    model = Document
    fields = ['title', 'uploadedfile']
    template_name = 'documents/document_add.html'
    success_url = reverse_lazy('documents:list')


class Edit_document(generic.UpdateView):
    model = Document
    fields = ['title', 'uploadedfile']
    template_name = 'documents/document_edit.html'
    success_url = reverse_lazy('documents:list')


class Delete_document(generic.DeleteView):
    model = Document
    success_url = reverse_lazy('documents:list')
    template_name = 'documents/document_delete.html'

    def dispatch(self, *args, **kwargs):
        return super(Delete_document, self).dispatch(*args, **kwargs)

templates/documents/document_add.html
{% extends "base.html" %}

{% block title %}document{% endblock %}

{% block documentactive %}class="active"{% endblock %}

{% block content %}

{% include "documents/document_form.html" with documentformtitle="Aggiungi Documento" documentformbutton="Aggiungi" %}

{% endblock %}

templates/documents/document_delete.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Document{% endblock %}

{% block documentactive %}class="active"{% endblock %}

{% block content %}
<div class="container">

	<h1>Elimina Documento</h1>
	Sicuro di voler eliminare questo documento?
	<form method="post">
		{% csrf_token %}
		<button type="submit" class="btn btn-danger">
			Elimina
		</button>
	</form>
</div>
<!-- /.container -->

{% endblock %}

templates/documents/document_edit.html
{% extends "base.html" %}

{% block title %}document{% endblock %}

{% block documentactive %}class="active"{% endblock %}

{% block content %}

{% include "documents/document_form.html" with documentformtitle="Modifica Documento" documentformbutton="Modifica" %}

{% endblock %}

templates/documents/document_form.html
{% load bootstrap3 %}

<div class="container">

	<h1>{{ documentformtitle }}</h1>
	<form method="post" action="" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Titolo</label>
				<div class="col-md-2">{{ form.title }}</div>
				<label class="col-md-2 control-label">File</label>
				<div class="col-md-2">{{ form.uploadedfile }}</div>
			</div>
		</div>
		<hr>
		<button type="submit" class="btn btn-primary">{{ documentformbutton }}</button></form>
</div>
<!-- /.container -->

templates/documents/document_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}Documenti{% endblock %}

{% block documentactive %}class="active"{% endblock %}

{% block additional_head %}
<script src="{% static 'jquery/jquery.tablesorter.min.js' %}"></script>
<script>
	$(document).ready(function() {
		$("#documentlist").tablesorter({
			headers : {
				1 : {
					sorter : false
				}
			}
		});
	}); 
</script>
{% endblock %}

{% block content %}
<div class="container">

	<h1>Elenco Documenti {% if perms.documents.add_document %}<a style="vertical-align: middle" class="btn btn-sm btn-primary" href="{% url 'documents:add' %}"><span class="glyphicon glyphicon-plus" ></span></a>{% endif %}</h1>

	{% if document_list %}

	<table class="table table-condesed table-striped tablesorter" id="documentlist">
		<thead>
			<tr>
				<th>Titolo</th>
                <th>Ultima modifica</th>
				<th>Comandi</th>
			</tr>
		</thead>
		<tbody>
			{% for document in document_list %}
			<tr>
				<td>{{ document.title }}</td>
                <td>{{ document.timestamp }}</td>
				<td>
                    <a href="{{ document.uploadedfile.url }}" target="_blank"><img src="{% static 'misc/edit.png'%}" /></a>
					{% if perms.documents.change_document %}<a href="{% url 'documents:edit' pk=document.pk %}"><img src="{% static 'misc/edit.png'%}" /></a>{% endif %}
					{% if perms.documents.delete_document %}<a href="{% url 'documents:delete' pk=document.pk %}"><img src="{% static 'misc/delete.png'%}" /></a>{% endif %}
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<div class="pagination">
		<span class="step-links">
        {% if document_list.has_previous %}
            <a href="?page={{ document_list.previous_page_number }}"><</a>
        {% endif %}

        <span class="current">
            Pagina {{ document_list.number }} di {{ document_list.paginator.num_pages }}
        </span>

        {% if document_list.has_next %}
            <a href="?page={{ document_list.next_page_number }}">></a>
        {% endif %}
    </span>
	</div>
	{% else %}
	<p>
		Nessun documento disponibile
	</p>
	{% endif %}
</div>
<!-- /.container -->

{% endblock %}