Djojo/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView
from engine.views import UserProfileDetailView
admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^users/', include('registration.backends.simple.urls')),
    
    url(r'^$','engine.views.home', name='home'),
    url(r'^dojo/', include('dojo.urls'), name='dojo'),
    url(r'^documents/', include('documents.urls', namespace='documents'), name='documents'),
    
    url(r'^users/(?P<slug>\w+)/$', UserProfileDetailView.as_view(), name="profile"),
    
    #fix per django 1.6
    #http://stackoverflow.com/questions/19985103/
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    
    url(r'^users/register/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register'),
)


urlpatterns += patterns('',
     (r'^static/(?P<path>.*)$', 'django.views.static.serve',
    # {'document_root': settings.MEDIA_ROOT}),
    #{'document_root': settings.MEDIA_ROOT, 'show_indexes': True},
    {'document_root': settings.STATIC_ROOT, 'show_indexes': True})
)

handler403 = 'engine.views.custom403'

blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'^$',views.index, name='index'),
    #url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<slug>.*)/$', views.detail, name='detail'),
)

dojo/urls.py
from django.contrib.auth.decorators import permission_required
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^ninja/$',views.ninja_list, name='ninja_list'),
    url(r'^ninja/new/$', views.ninja_add, name='ninja_add'),
    url(r'^ninja/(?P<pk>\d+)/edit/$', views.ninja_edit, name="ninja_edit"),
    url(r'^ninja/(?P<pk>\d+)/delete/$', permission_required('dojo.delete_ninja', raise_exception=True)(views.Ninja_delete.as_view()), name="ninja_delete"),
    url(r'^ninja/(?P<pk>\d+)/$', permission_required('dojo.view_ninja', raise_exception=True)(views.Ninja_detail.as_view()), name='ninja_detail'),
    
    url(r'^mentor/$',views.mentor_list, name='mentor_list'),
    url(r'^mentor/new/$', views.mentor_add, name='mentor_add'),
    url(r'^mentor/(?P<pk>\d+)/edit/$', views.mentor_edit, name="mentor_edit"),
    url(r'^mentor/(?P<pk>\d+)/delete/$', permission_required('dojo.delete_mentor', raise_exception=True)(views.Mentor_delete.as_view()), name="mentor_delete"),
    #url(r'^(?P<slug>.*)/$', views.detail, name='detail'),

    url(r'^event/$',views.event_list, name='event_list'),
    url(r'^event/new/$', views.event_add, name='event_add'),
    url(r'^event/(?P<pk>\d+)/edit/$', views.event_edit, name="event_edit"),
    url(r'^event/(?P<pk>\d+)/delete/$', permission_required('dojo.delete_event', raise_exception=True)(views.Event_delete.as_view()), name="event_delete"),
    url(r'^event/(?P<pk>\d+)/$', permission_required('dojo.view_event', raise_exception=True)(views.Event_detail.as_view()), name='event_detail'),

    url(r'^skill/$',views.skill_list, name='skill_list'),
    url(r'^skill/new/$', views.skill_add, name='skill_add'),
    url(r'^skill/(?P<pk>\d+)/edit/$', views.skill_edit, name="skill_edit"),
    url(r'^skill/(?P<pk>\d+)/delete/$', permission_required('dojo.delete_skill', raise_exception=True)(views.Skill_delete.as_view()), name="skill_delete"),

)

dojo/models.py
import datetime
from django.db import models
from dateutil.relativedelta import relativedelta
from tinymce.models import HTMLField

class Level(models.Model):
    
    title = models.CharField('Titolo', max_length=100)
    image = models.ImageField('Immagine', upload_to='.', blank=True)
    value = models.IntegerField('Valore')
    
    def __unicode__(self):
        return self.title
    
    def thumbnail(self):
        return u'<img src="%s" />' % (self.image.url)
    thumbnail.short_description = 'Immagine'
    thumbnail.allow_tags = True


class Skill(models.Model):
    title = models.CharField('Titolo', max_length=200)
    color = models.CharField('Colore', max_length=10, blank=True)
    notes = HTMLField('Note', blank=True)

    def __unicode__(self):
        return self.title


class Ninja(models.Model):
    name = models.CharField('Nome', max_length=50)
    surname = models.CharField('Cognome', max_length=50)
    birthday = models.DateField('Data di nascita', blank=True, null=True)
    photo = models.ImageField('Foto', upload_to='./photos', blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cellphone = models.CharField('Cellulare', max_length=15, blank=True)
    email = models.EmailField('Email', blank=True)
    tutorpermission = models.BooleanField('Manleva', default=False)
    photopermission = models.BooleanField('Permesso Foto', default=False)
    tutorname = models.CharField('Nome Accompagnatore', max_length=50, blank=True)
    tutorsurname = models.CharField('Cognome Accompagnatore', max_length=50, blank=True)
    tutoremail = models.EmailField('Email', blank=True)
    tutorcellphone = models.CharField('Cell Accompagnatore', max_length=15, blank=True)
    notes = HTMLField('Note', blank=True)   
    slug = models.CharField(max_length=200)
    
    def getAge(self):
        return relativedelta(datetime.date.today(), self.birthday).years
    getAge.short_description = 'Eta'
    getAge.integer = True
    
    def __unicode__(self):
        return self.name + ' ' + self.surname
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = '%s%s' % (
                self.name, self.surname
            )
        super(Ninja, self).save(*args, **kwargs)


class Mentor(models.Model):
    name = models.CharField('Nome', max_length=50)
    surname = models.CharField('Cognome', max_length=50)
    birthday = models.DateField('Data di nascita', blank=True, null=True)
    cellphone = models.CharField('Cellulare', max_length=15, blank=True)
    email = models.EmailField('Email', blank=True)
    notes = HTMLField('Note', blank=True)   
    slug = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.name + ' ' + self.surname
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = '%s%s' % (
                self.name, self.surname
            )
        super(Mentor, self).save(*args, **kwargs)


class Event(models.Model):
    title = models.CharField('Titolo', max_length=200)
    pub_date = models.DateField('Data evento')
    location = models.CharField('Luogo', max_length=200, blank=True)
    activity = HTMLField(blank=True)
    participants = models.ManyToManyField(Ninja, blank=True)
    mentors = models.ManyToManyField(Mentor, blank=True)
    notes = HTMLField('Note', blank=True)
    slug = models.CharField(max_length=200)

    def __unicode__(self):
        return unicode(self.pub_date)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = '%s%s%s' % (
                self.pub_date.day, self.pub_date.month, self.pub_date.year
            )
            # a=Event.objects.get(pk=1)
            self.partecipantsnumber = 0
        super(Event, self).save(*args, **kwargs)

dojo/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from django.contrib.auth.decorators import permission_required
from django.views.generic.edit import DeleteView
from django.views import generic
from .forms import NinjaForm, MentorForm, EventForm, SkillForm
from django.http import HttpResponseRedirect

from .models import Ninja, Event, Mentor, Skill

@permission_required('dojo.view_ninja', raise_exception=True)
def ninja_list(request):
    
    ninja_list = Ninja.objects.order_by('surname')
    paginator = Paginator(ninja_list, 25)
    
    page = request.GET.get('page')
    try:
        ninja_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        ninja_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        ninja_list = paginator.page(paginator.num_pages)

    return render_to_response('dojo/ninja/ninja_list.html', {"ninja_list": ninja_list}, context_instance=RequestContext(request))


@permission_required('dojo.add_ninja', raise_exception=True)
def ninja_add(request):
    if request.method == 'POST':
        form = NinjaForm(data=request.POST)
        
        if form.is_valid():
            
            model_instance = form.save(commit=False)
            model_instance.slug = '%s%s' % (
                model_instance.name, model_instance.surname
            )
            model_instance.save()
            return HttpResponseRedirect("/dojo/ninja/")
    else:
        form = NinjaForm()
    return render_to_response("dojo/ninja/ninja_add.html", {'form' : form }, context_instance=RequestContext(request))


@permission_required('dojo.change_ninja', raise_exception=True)
def ninja_edit(request, pk):
    instance = get_object_or_404(Ninja, pk=pk)
    if request.method == "POST":
        form = NinjaForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/dojo/ninja/")
    else:
        form = NinjaForm(instance=instance)
    return render_to_response("dojo/ninja/ninja_edit.html", {'form' : form }, context_instance=RequestContext(request))
        
        
class Ninja_delete(DeleteView):
    model = Ninja
    success_url = '/dojo/ninja/'
    template_name = 'dojo/ninja/ninja_delete.html'
    
    def dispatch(self, *args, **kwargs):
        return super(Ninja_delete, self).dispatch(*args, **kwargs)


class Ninja_detail(generic.DetailView):
    model = Ninja
    template_name = 'dojo/ninja/ninja_detail.html'


@permission_required('dojo.view_mentor', raise_exception=True)
def mentor_list(request):
    
    mentor_list = Mentor.objects.order_by('surname')
    paginator = Paginator(mentor_list, 25)
    
    page = request.GET.get('page')
    try:
        mentor_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        mentor_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        mentor_list = paginator.page(paginator.num_pages)

    return render_to_response('dojo/mentor/mentor_list.html', {"mentor_list": mentor_list}, context_instance=RequestContext(request))


@permission_required('dojo.add_mentor', raise_exception=True)
def mentor_add(request):
    if request.method == 'POST':
        form = MentorForm(data=request.POST)
        
        if form.is_valid():
            
            model_instance = form.save(commit=False)
            model_instance.slug = '%s%s' % (
                model_instance.name, model_instance.surname
            )
            model_instance.save()
            return HttpResponseRedirect("/dojo/mentor/")
    else:
        form = MentorForm()
    return render_to_response("dojo/mentor/mentor_add.html", {'form' : form }, context_instance=RequestContext(request))


@permission_required('dojo.change_mentor', raise_exception=True)
def mentor_edit(request, pk):
    instance = get_object_or_404(Mentor, pk=pk)
    if request.method == "POST":
        form = MentorForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/dojo/mentor/")
    else:
        form = MentorForm(instance=instance)
    return render_to_response("dojo/mentor/mentor_edit.html", {'form' : form }, context_instance=RequestContext(request))


class Mentor_delete(DeleteView):
    model = Mentor
    success_url = '/dojo/mentor/'
    template_name = 'dojo/mentor/mentor_delete.html'
    
    def dispatch(self, *args, **kwargs):
        return super(Mentor_delete, self).dispatch(*args, **kwargs)


@permission_required('dojo.view_event', raise_exception=True)
def event_list(request):

    event_list = Event.objects.order_by('-pub_date')
    paginator = Paginator(event_list, 25)

    page = request.GET.get('page')
    try:
        event_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        event_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        event_list = paginator.page(paginator.num_pages)

    return render_to_response('dojo/event/event_list.html', {"event_list": event_list}, context_instance=RequestContext(request))


@permission_required('dojo.add_event', raise_exception=True)
def event_add(request):
    if request.method == 'POST':
        form = EventForm(data=request.POST)

        if form.is_valid():

            model_instance = form.save(commit=False)
            model_instance.slug = '%s%s%s' % (
                model_instance.pub_date.day, model_instance.pub_date.month, model_instance.pub_date.year
            )
            model_instance.save()
            return HttpResponseRedirect("/dojo/event/")
    else:
        form = EventForm()
    return render_to_response("dojo/event/event_add.html", {'form' : form }, context_instance=RequestContext(request))


@permission_required('dojo.change_event', raise_exception=True)
def event_edit(request, pk):
    instance = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        form = EventForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/dojo/event/")
    else:
        form = EventForm(instance=instance)
    return render_to_response("dojo/event/event_edit.html", {'form' : form }, context_instance=RequestContext(request))


class Event_delete(DeleteView):
    model = Event
    success_url = '/dojo/event/'
    template_name = 'dojo/event/event_delete.html'

    def dispatch(self, *args, **kwargs):
        return super(Event_delete, self).dispatch(*args, **kwargs)

class Event_detail(generic.DetailView):
    model = Event
    template_name = 'dojo/event/event_detail.html'


@permission_required('dojo.view_skill', raise_exception=True)
def skill_list(request):

    skill_list = Skill.objects.order_by('title')
    paginator = Paginator(skill_list, 25)

    page = request.GET.get('page')
    try:
        skill_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        skill_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        skill_list = paginator.page(paginator.num_pages)

    return render_to_response('dojo/skill/skill_list.html', {"skill_list": skill_list}, context_instance=RequestContext(request))


@permission_required('dojo.add_skill', raise_exception=True)
def skill_add(request):
    if request.method == 'POST':
        form = SkillForm(data=request.POST)

        if form.is_valid():

            form.save()
            return HttpResponseRedirect("/dojo/skill/")
    else:
        form = SkillForm()
    return render_to_response("dojo/skill/skill_add.html", {'form' : form }, context_instance=RequestContext(request))


@permission_required('dojo.change_skill', raise_exception=True)
def skill_edit(request, pk):
    instance = get_object_or_404(Skill, pk=pk)
    if request.method == "POST":
        form = SkillForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/dojo/skill/")
    else:
        form = SkillForm(instance=instance)
    return render_to_response("dojo/skill/skill_edit.html", {'form' : form }, context_instance=RequestContext(request))


class Skill_delete(DeleteView):
    model = Skill
    success_url = '/dojo/skill/'
    template_name = 'dojo/skill/skill_delete.html'

    def dispatch(self, *args, **kwargs):
        return super(Skill_delete, self).dispatch(*args, **kwargs)

templates/dojo/ninja/ninja_add.html
{% extends "base.html" %}

{% block title %}Ninja{% endblock %}

{% block ninjaactive %}class="active"{% endblock %}

{% block content %}

{% include "dojo/ninja/ninja_form.html" with ninjaformtitle="Aggiungi Ninja" ninjaformbutton="Aggiungi" %}

{% endblock %}

templates/dojo/ninja/ninja_delete.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Ninja{% endblock %}

{% block ninjaactive %}class="active"{% endblock %}

{% block content %}
<div class="container">

	<h1>Elimina Ninja</h1>
	Sicuro di voler eliminare questo ninja?
	<form method="post">
		{% csrf_token %}
		<button type="submit" class="btn btn-danger">
			Elimina
		</button>
	</form>
</div>
<!-- /.container -->

{% endblock %}

templates/dojo/ninja/ninja_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Ninja{% endblock %}

{% block ninjaactive %}class="active"{% endblock %}

{% block content %}
<div class="container">
<div class="row">
	<h1>{{ ninja.name }} {{ ninja.surname }}</h1>
    </div>
    <div class=row">
        Data di nascita {{ ninja.birthday }} ({{ ninja.getAge }} anni)
    </div>

    <div class=row">
        Note:
        <div>{{ ninja.notes }}</div>
    </div>


</div>
<!-- /.container -->

{% endblock %}

templates/dojo/ninja/ninja_edit.html
{% extends "base.html" %}

{% block title %}Ninja{% endblock %}

{% block ninjaactive %}class="active"{% endblock %}

{% block content %}

{% include "dojo/ninja/ninja_form.html" with ninjaformtitle="Modifica Ninja" ninjaformbutton="Modifica" %}

{% endblock %}

templates/dojo/ninja/ninja_form.html
{% load bootstrap3 %}
{% load staticfiles %}

<script src="{% static 'jquery-ui/js/jquery-ui-1.10.4.custom.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'jquery-ui/css/redmond/jquery-ui-1.10.4.custom.min.css' %}" />
<script src="{% static 'select2/select2.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'select2/select2.css' %}"/>
<script>
    $(document).ready(function () {
        $('#id_skills').select2({ width: '100%' });
    });

	$(function() {
		$("#id_birthday").datepicker({
			changeMonth : true,
			changeYear : true,
			yearRange: "1984:2014",
			dateFormat: "dd/mm/yy"
		});
	}); 
</script>
<style>
div.ui-datepicker {
    font-size: 10px;
    color: #222222;
}
.ui-widget-header {
    color: #222222;
}
</style>

<div class="container">

	<h1>{{ ninjaformtitle }}</h1>
	<form method="post" action=""	>
		{% csrf_token %}
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Nome *</label>
				<div class="col-md-2">
					{{ form.name }}
				</div>
				<label class="col-md-2 control-label">Cognome *</label>
				<div class="col-md-2">
					{{ form.surname }}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Data di nascita</label>
				<div class="col-md-2">
					{{ form.birthday }}
				</div>
				<label class="col-md-2 control-label">Manleva</label>
				<div class="col-md-2">
					{{ form.tutorpermission }}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Email</label>
				<div class="col-md-2">
					{{ form.email }}
				</div>
				<label class="col-md-2 control-label">Cellulare</label>
				<div class="col-md-2">
					{{ form.cellphone }}
				</div>
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Nome accompagnatore</label>
				<div class="col-md-2">
					{{ form.tutorname }}
				</div>
				<label class="col-md-2 control-label">Cognome accompagnatore</label>
				<div class="col-md-2">
					{{ form.tutorsurname }}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Email</label>
				<div class="col-md-2">
					{{ form.tutoremail }}
				</div>
				<label class="col-md-2 control-label">Cellulare</label>
				<div class="col-md-2">
					{{ form.tutorcellphone }}
				</div>
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Permesso Foto</label>
				<div class="col-md-2">
					{{ form.photopermission }}
				</div>
				<label class="col-md-2 control-label">Foto</label>
				<div class="col-md-2">
					{{ form.photo }}
				</div>
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Skill</label>
				<div class="col-md-6">
					{{ form.skills }}
				</div>
			</div>
		</div>
        <hr>
		<div class="row">
			<div class="form-group">
				<label class="col-md-2 control-label">Note</label>
				<div class="col-md-6">
					{{ form.notes }}
				</div>
			</div>
		</div>
		<hr>
		<button type="submit" class="btn btn-primary">
			{{ ninjaformbutton }}
		</button>
	</form>
</div>
<!-- /.container -->

templates/dojo/ninja/ninja_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}Ninja{% endblock %}

{% block ninjaactive %}class="active"{% endblock %}

{% block additional_head %}
<script src="{% static 'jquery/jquery.tablesorter.min.js' %}"></script>
<script>
	$(document).ready(function() {
		$("#ninjalist").tablesorter({
			sortList : [[1, 0]],
			headers : {
				3 : {
					sorter : false
				},
				5 : {
					sorter : false
				},
				6 : {
					sorter : false
				}
			}
		});
	}); 

</script>
{% endblock %}

{% block content %}
<div class="container">

    <h1>Elenco Ninja {% if perms.dojo.add_ninja %}<a style="vertical-align: middle" class="btn btn-sm btn-primary"
                                                     href="{% url 'dojo.views.ninja_add' %}"><span
            class="glyphicon glyphicon-plus"></span></a>{% endif %}</h1>

    {% if ninja_list %}

    <table class="table table-condesed table-striped tablesorter" id="ninjalist">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Età</th>
            <!--<th>Livello</th>-->
            <th>Manleva</th>
            <th>Eventi Partecipati</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for ninja in ninja_list %}
        <tr>
            <td><a href="{% url 'ninja_detail' pk=ninja.pk %}">{{ ninja.name }}</a></td>
            <td>{{ ninja.surname }}</td>
            <td>{% if ninja.getAge > 0 %}{{ ninja.getAge }}{% endif %}</td>
            <!--<td>{% if ninja.level != None %}{{ ninja.level }}{% endif %}</td>-->
            <td>{% if ninja.parentpermission %}<span class="glyphicon glyphicon-ok"></span>{% endif %}</td>
            <td>{% if ninja.event_set.count > 0 %}
                <a href="#" data-toggle="modal" data-target=".bs-{{ ninja.pk }}-modal-sm">{{ ninja.event_set.count }}</a>
                <div class="modal fade bs-{{ ninja.pk }}-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <span class="modal-title">Eventi partecipati</span>
                            </div>
                            <div class="modal-body">
                                <table class="table table-condesed table-striped">
                                {% for event in ninja.event_set.all|dictsortreversed:"pub_date" %}
                                    <tr>
                                        <td><a href="{% url 'event_detail' pk=event.pk %}">{{ event.title }}</a></td>
                                        <td>{{ event.pub_date }}</td>
                                    </tr>
                                {% endfor %}
                                </table>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary btn-xs" data-dismiss="modal">Chiudi</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </td>
            <td>
                {% if perms.dojo.change_ninja %}<a href="{% url 'ninja_edit' pk=ninja.pk %}"><img
                    src="{% static 'misc/edit.png'%}"/></a>{% endif %}
                {% if perms.dojo.delete_ninja %}<a href="{% url 'ninja_delete' pk=ninja.pk %}"><img
                    src="{% static 'misc/delete.png'%}"/></a>{% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links"> {% if ninja_list.has_previous %} <a
                href="?page={{ ninja_list.previous_page_number }}"><</a> {% endif %} <span class="current"> Pagina {{ ninja_list.number }} di {{ ninja_list.paginator.num_pages }} </span> {% if ninja_list.has_next %} <a
                href="?page={{ ninja_list.next_page_number }}">></a> {% endif %} </span>
    </div>
    {% else %}
    <p>
        Nessun ninja disponibile
    </p>
    {% endif %}
</div>
<!-- /.container -->

{% endblock %}