Djojo/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView
from engine.views import UserProfileDetailView
admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^users/', include('registration.backends.simple.urls')),
    
    url(r'^$','engine.views.home', name='home'),
    url(r'^dojo/', include('dojo.urls'), name='dojo'),
    url(r'^documents/', include('documents.urls', namespace='documents'), name='documents'),
    
    url(r'^users/(?P<slug>\w+)/$', UserProfileDetailView.as_view(), name="profile"),
    
    #fix per django 1.6
    #http://stackoverflow.com/questions/19985103/
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    
    url(r'^users/register/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register'),
)


urlpatterns += patterns('',
     (r'^static/(?P<path>.*)$', 'django.views.static.serve',
    # {'document_root': settings.MEDIA_ROOT}),
    #{'document_root': settings.MEDIA_ROOT, 'show_indexes': True},
    {'document_root': settings.STATIC_ROOT, 'show_indexes': True})
)

handler403 = 'engine.views.custom403'

blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'^$',views.index, name='index'),
    #url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<slug>.*)/$', views.detail, name='detail'),
)

dojo/models.py
import datetime
from django.db import models
from dateutil.relativedelta import relativedelta
from tinymce.models import HTMLField

class Level(models.Model):
    
    title = models.CharField('Titolo', max_length=100)
    image = models.ImageField('Immagine', upload_to='.', blank=True)
    value = models.IntegerField('Valore')
    
    def __unicode__(self):
        return self.title
    
    def thumbnail(self):
        return u'<img src="%s" />' % (self.image.url)
    thumbnail.short_description = 'Immagine'
    thumbnail.allow_tags = True


class Skill(models.Model):
    title = models.CharField('Titolo', max_length=200)
    color = models.CharField('Colore', max_length=10, blank=True)
    notes = HTMLField('Note', blank=True)

    def __unicode__(self):
        return self.title


class Ninja(models.Model):
    name = models.CharField('Nome', max_length=50)
    surname = models.CharField('Cognome', max_length=50)
    birthday = models.DateField('Data di nascita', blank=True, null=True)
    photo = models.ImageField('Foto', upload_to='./photos', blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cellphone = models.CharField('Cellulare', max_length=15, blank=True)
    email = models.EmailField('Email', blank=True)
    tutorpermission = models.BooleanField('Manleva', default=False)
    photopermission = models.BooleanField('Permesso Foto', default=False)
    tutorname = models.CharField('Nome Accompagnatore', max_length=50, blank=True)
    tutorsurname = models.CharField('Cognome Accompagnatore', max_length=50, blank=True)
    tutoremail = models.EmailField('Email', blank=True)
    tutorcellphone = models.CharField('Cell Accompagnatore', max_length=15, blank=True)
    notes = HTMLField('Note', blank=True)   
    slug = models.CharField(max_length=200)
    
    def getAge(self):
        return relativedelta(datetime.date.today(), self.birthday).years
    getAge.short_description = 'Eta'
    getAge.integer = True
    
    def __unicode__(self):
        return self.name + ' ' + self.surname
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = '%s%s' % (
                self.name, self.surname
            )
        super(Ninja, self).save(*args, **kwargs)


class Mentor(models.Model):
    name = models.CharField('Nome', max_length=50)
    surname = models.CharField('Cognome', max_length=50)
    birthday = models.DateField('Data di nascita', blank=True, null=True)
    cellphone = models.CharField('Cellulare', max_length=15, blank=True)
    email = models.EmailField('Email', blank=True)
    notes = HTMLField('Note', blank=True)   
    slug = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.name + ' ' + self.surname
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = '%s%s' % (
                self.name, self.surname
            )
        super(Mentor, self).save(*args, **kwargs)


class Event(models.Model):
    title = models.CharField('Titolo', max_length=200)
    pub_date = models.DateField('Data evento')
    location = models.CharField('Luogo', max_length=200, blank=True)
    activity = HTMLField(blank=True)
    participants = models.ManyToManyField(Ninja, blank=True)
    mentors = models.ManyToManyField(Mentor, blank=True)
    notes = HTMLField('Note', blank=True)
    slug = models.CharField(max_length=200)

    def __unicode__(self):
        return unicode(self.pub_date)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = '%s%s%s' % (
                self.pub_date.day, self.pub_date.month, self.pub_date.year
            )
            # a=Event.objects.get(pk=1)
            self.partecipantsnumber = 0
        super(Event, self).save(*args, **kwargs)

engine/views.py
from django.shortcuts import render
from django.contrib.auth.views import login
from django.contrib.auth.decorators import login_required
from registration.backends.simple.views import RegistrationView
from django.views.generic import ListView, DetailView
from django.contrib.auth import get_user_model
from engine.models import UserProfile

def home(request):
    if (request.user.is_authenticated()):
        return render(request, 'engine/home.html')
    return login(request, template_name='engine/home.html')

@login_required
def profile(request):
    return render(request, template_name='engine/profile.html')

def custom403(request):
    return render(request, template_name='engine/403.html')



class UserProfileDetailView(DetailView):
    model = get_user_model()
    slug_field = "username"
    template_name = "engine/profile.html"

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user    

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		{% load staticfiles %}
		{% load bootstrap3 %}

		<script src="{% static 'jquery/jquery-2.1.0.min.js' %}"></script>

        {% bootstrap_css %}
		{% bootstrap_javascript %}

		<link rel="shortcut icon" href="{% static 'misc/favicon.ico' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'misc/css/style.css' %}" />

		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Ubuntu:400,700&#038;subset=latin,latin-ext" type='text/css' media='all' />

		{% block additional_head %}{% endblock %}

		<title>{% block title %}{% endblock %}</title>
	</head>
	<body>
		<div class="wrapper">
			<div class="container">
				<nav class="navbar navbar-default" role="navigation">
					<div class="container">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<span class="navbar-brand">Dojo</span>
						</div>
						<div class="navbar-collapse collapse">
							<ul class="nav navbar-nav">
								<li {% block homeactive %}{% endblock %}>
									<a href="{% url 'engine.views.home' %}"><span class="glyphicon glyphicon-home"></span> Home</a>
								</li>
								{% if perms.dojo.view_event %}
								<li {% block eventactive %}{% endblock %}>
									<a href="{% url 'dojo.views.event_list' %}"><span class="glyphicon glyphicon-calendar"></span> Eventi</a>
								</li>
								{% endif %}
                                {% if perms.dojo.view_ninja %}
								<li {% block ninjaactive %}{% endblock %}>
									<a href="{% url 'dojo.views.ninja_list' %}"><span class="glyphicon glyphicon-list"></span> Ninja</a>
								</li>
								{% endif %}
								{% if perms.dojo.view_mentor %}
								<li {% block mentoractive %}{% endblock %}>
									<a href="{% url 'dojo.views.mentor_list' %}"><span class="glyphicon glyphicon-tower"></span> Mentor</a>
								</li>
								{% endif %}
                                {% if perms.dojo.view_skill %}
								<li {% block skillactive %}{% endblock %}>
									<a href="{% url 'dojo.views.skill_list' %}"><span class="glyphicon glyphicon-star"></span> Skill</a>
								</li>
								{% endif %}
							</ul>
							{% if user.is_authenticated %}
							<ul class="nav navbar-nav navbar-right">
								<li id="nav-username">
									<a href="{% url 'profile' slug=user.username %}"> <span class="glyphicon glyphicon-user"></span> {{ user.get_username }}</a>
								</li>
								{% if user.is_staff %}
								<li>
									<a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-cog"></span> Admin</a>
								</li>
								{% endif %}
								<li>
									<a href="{% url 'django.contrib.auth.views.logout' %}"><span class="glyphicon glyphicon-off"></span> Logout &nbsp</a>
								</li>
							</ul>
							{% endif %}
							
						</div><!--/.navbar-collapse -->
					</div>
				</nav>
			</div>
			{% block content %}
			{% endblock %}
			<div id="page-footer">
				<div class="container">
					<footer>
						<div class="pull-right">
							<small>2014 - <a href="https://github.com/doc90/Djojo">github</a> - {{ VERSION }}</small>
						</div>
					</footer>
				</div>
			</div>
		</div>
	</body>
</html>